version: '3'
services:
    conda:
        build: .
        #image: "continuumio/anaconda3"
        ports:
            - "8888:8888"
            - "6006:6006"
        volumes:
            - ./notebooks:/opt/notebooks
        command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
